volumes:
  postgres-data: {}

networks:
  my-app-network:

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - my-app-network
    environment:
      POSTGRES_USER: byte_cat
      POSTGRES_PASSWORD: byte_cat
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
#    env_file:
#      - .env
  app:
    build: .
    container_name: image-resizer-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
        - my-app-network
    environment:
      DB_HOST: db
      DB_USER: byte_cat
      DB_PASSWORD: byte_cat
      DB_NAME: image_db
#    env_file:
#        - .env
