# FastAPI

# curl --location 'http://localhost:8000/images?depth_min=9000&depth_max=9100'
GET http://localhost:8000/images?depth_min=9000&depth_max=9100

###

# API to get the response in image format
# curl --location 'http://localhost:8000/images/pixel_data?depth_min=9000&depth_max=9100'
GET http://localhost:8000/images/pixel_data?depth_min=9000&depth_max=9100

###